Drop table Nationalite Cascade;
Drop table Contributeur Cascade;
Drop table Auteur Cascade;
Drop table Acteur Cascade;

Drop table Realisateur Cascade;
Drop table Interprete Cascade;
Drop table Compositeur Cascade;
Drop table Genre Cascade
Drop table Editeur Cascade;
Drop table Ressources Cascade;
Drop table AssocGenre Cascade;
Drop table Livre Cascade;
Drop table Film Cascade;
Drop table EnregistrementMusical Cascade;
Drop table Personnel Cascade;
Drop table Adherent Cascade;
Drop table Etat Cascade;
Drop table Exemplaire Cascade;
Drop table AssocPret Cascade;
Drop table Sanction Cascade;
